Repository matekasse/matekasse, pull requests merged in 2021-08, with the labels that each got.

#37 Add license to package.json
  api/package.json
  app/package.json
Labels: enhancement

#81 Build arm docker image
  .github/workflows/build-latest.yaml
  Dockerfile
  README.md
Labels: enhancement, CI

#90 Remove all Paypal features
  api/init-scripts/init-users.js
  api/src/controller/transaction-controller.ts
  api/src/controller/user-controller.ts
  api/src/entity/user.ts
  api/src/initial-start-up-configuration.ts
  api/src/services/user-service.ts
  api/src/test/products-tags.test.ts
  api/src/test/transactions.test.ts
  api/src/test/userUtils.ts
  api/src/test/users.test.ts
  api/src/test/warehouse-transaction.test.ts
  app/README.md
  app/src/components/admin-page/users-tab.vue
  app/src/components/user-page/change-user-names-modal.vue
  app/src/components/user-page/user-page.vue
Labels: Backend, Frontend

#103 Set modal default values when opening the modal
  app/src/components/admin-page/create-warehouse-transaction-modal.vue
  app/src/components/admin-page/edit-product-modal.vue
  app/src/components/admin-page/topup-modal.vue
  app/src/components/user-page/change-user-names-modal.vue
Labels: bug, Frontend

#108 Build container images for releases
  .github/workflows/build-latest-testing-docker-image.yaml
  .github/workflows/build-release-docker-image.yaml
  README.md
Labels: CI

#79 Enable TypeScript features
  api/init-scripts/init-manufacturers.js
  api/init-scripts/init-products.js
  api/init-scripts/init-tags.js
  api/init-scripts/init-users.js
  api/init-scripts/init-warehouse-transactions.js
  api/init-scripts/post.js
  api/package.json
  api/src/config/config.ts
  api/src/config/environment-variables.ts
  api/src/controller/constants-controller.ts
  api/src/controller/manufacturer-controller.ts
  api/src/controller/product-controller.ts
  api/src/controller/tag-controller.ts
  api/src/controller/transaction-controller.ts
  api/src/controller/user-controller.ts
  api/src/controller/warehouse-transaction-controller.ts
  api/src/entity/manufacturer.ts
  api/src/entity/product.ts
  api/src/entity/tag.ts
  api/src/entity/transaction.ts
  api/src/entity/user.ts
  api/src/entity/warehouse-transaction.ts
  api/src/module/authentication.ts
  api/src/router/constants-router.ts
  api/src/services/constants-service.ts
  api/src/services/database.ts
  api/src/services/manufacturer-service.ts
  api/src/services/product-service.ts
  api/src/services/tag-service.ts
  api/src/services/transaction-service.ts
  api/src/services/user-service.ts
  api/src/services/warehouse-transaction-service.ts
  api/src/test/constants.test.ts
  api/src/test/manufacturer.test.ts
  api/src/test/products-tags.test.ts
  api/src/test/products.test.ts
  api/src/test/tags.test.ts
  api/src/test/transactions.test.ts
  api/src/test/userUtils.ts
  api/src/test/users.test.ts
  api/src/test/warehouse-transaction.test.ts
  api/tsconfig.json
  yarn.lock
Labels: enhancement, Backend
