Repository matekasse/matekasse, pull requests merged in 2021-09, with the labels that each got.

#171 Improve tests and add authentication tests
  api/src/test/authentication.test.ts
  api/src/test/constants.test.ts
  api/src/test/manufacturer.test.ts
  api/src/test/products-tags.test.ts
  api/src/test/products.test.ts
  api/src/test/tags.test.ts
  api/src/test/transactions.test.ts
  api/src/test/users.test.ts
  api/src/test/warehouse-transaction.test.ts
Labels: Backend

#166 Add database migrations
  README.md
  api/README.md
  api/package.json
  api/src/config/config.ts
  api/src/config/environment-variables.ts
  api/src/initial-start-up-configuration.ts
  api/src/migrations/1629393037158-CreateDatabase.ts
  docker-compose.yaml
Labels: enhancement, Backend

#101 Support other currencies
  api/src/entity/constants.ts
  api/src/initial-start-up-configuration.ts
  api/src/migrations/1632332574939-add-currencySymbol-constant.ts
  api/src/router/constants-router.ts
  api/src/router/router.ts
  api/src/services/constants-service.ts
  api/src/test/constants.test.ts
  app/src/components/admin-page/admin-page.vue
  app/src/components/admin-page/constants-tab.vue
  app/src/components/admin-page/create-warehouse-transaction-modal.vue
  app/src/components/admin-page/edit-product-modal.vue
  app/src/components/admin-page/product-tab.vue
  app/src/components/admin-page/topup-modal.vue
  app/src/components/admin-page/users-tab.vue
  app/src/components/admin-page/warehouse-tab.vue
  app/src/components/auth/login.vue
  app/src/components/auth/register.vue
  app/src/components/product-page/product-card.vue
  app/src/components/user-page/user-page.vue
  app/src/store/index.js
  app/src/utils/api-connector.js
  app/src/views/home-view.vue
Labels: enhancement, Backend, Frontend
